-- Oracle schema and deterministic fixtures for the PL/SQL hands-on exercises.
BEGIN
  FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN
    ('AUDIT_LOG','ERROR_LOG','TRANSACTIONS','LOANS','ACCOUNTS','EMPLOYEES','CUSTOMERS')) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

CREATE TABLE Customers (
  CustomerID NUMBER PRIMARY KEY,
  Name VARCHAR2(100) NOT NULL,
  DOB DATE NOT NULL,
  Balance NUMBER(15,2) DEFAULT 0 NOT NULL,
  IsVIP CHAR(1) DEFAULT 'N' NOT NULL CHECK (IsVIP IN ('Y','N')),
  LastModified DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE Accounts (
  AccountID NUMBER PRIMARY KEY,
  CustomerID NUMBER NOT NULL REFERENCES Customers(CustomerID),
  AccountType VARCHAR2(20) NOT NULL,
  Balance NUMBER(15,2) DEFAULT 0 NOT NULL,
  LastModified DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE Transactions (
  TransactionID NUMBER PRIMARY KEY,
  AccountID NUMBER NOT NULL REFERENCES Accounts(AccountID),
  TransactionDate DATE DEFAULT SYSDATE NOT NULL,
  Amount NUMBER(15,2) NOT NULL,
  TransactionType VARCHAR2(10) NOT NULL CHECK (TransactionType IN ('Deposit','Withdrawal'))
);

CREATE TABLE Loans (
  LoanID NUMBER PRIMARY KEY,
  CustomerID NUMBER NOT NULL REFERENCES Customers(CustomerID),
  LoanAmount NUMBER(15,2) NOT NULL,
  InterestRate NUMBER(7,4) NOT NULL,
  StartDate DATE NOT NULL,
  EndDate DATE NOT NULL
);

CREATE TABLE Employees (
  EmployeeID NUMBER PRIMARY KEY,
  Name VARCHAR2(100) NOT NULL,
  Position VARCHAR2(50),
  Salary NUMBER(15,2) NOT NULL,
  Department VARCHAR2(50) NOT NULL,
  HireDate DATE NOT NULL
);

CREATE TABLE Audit_Log (
  AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  EventName VARCHAR2(100) NOT NULL,
  EventDetails VARCHAR2(4000),
  EventDate DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE Error_Log (
  ErrorID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ProcedureName VARCHAR2(100) NOT NULL,
  ErrorMessage VARCHAR2(4000) NOT NULL,
  ErrorDate DATE DEFAULT SYSDATE NOT NULL
);

INSERT INTO Customers(CustomerID, Name, DOB, Balance) VALUES (1, 'John Doe', DATE '1950-05-15', 1000);
INSERT INTO Customers(CustomerID, Name, DOB, Balance) VALUES (2, 'Jane Smith', DATE '1990-07-20', 15000);
INSERT INTO Accounts(AccountID, CustomerID, AccountType, Balance) VALUES (1, 1, 'Savings', 1000);
INSERT INTO Accounts(AccountID, CustomerID, AccountType, Balance) VALUES (2, 2, 'Checking', 1500);
INSERT INTO Transactions(TransactionID, AccountID, TransactionDate, Amount, TransactionType) VALUES (1, 1, SYSDATE, 200, 'Deposit');
INSERT INTO Transactions(TransactionID, AccountID, TransactionDate, Amount, TransactionType) VALUES (2, 2, SYSDATE, 300, 'Withdrawal');
INSERT INTO Loans(LoanID, CustomerID, LoanAmount, InterestRate, StartDate, EndDate)
  VALUES (1, 1, 5000, 5, SYSDATE, SYSDATE + 15);
INSERT INTO Employees(EmployeeID, Name, Position, Salary, Department, HireDate)
  VALUES (1, 'Alice Johnson', 'Manager', 70000, 'HR', DATE '2015-06-15');
INSERT INTO Employees(EmployeeID, Name, Position, Salary, Department, HireDate)
  VALUES (2, 'Bob Brown', 'Developer', 60000, 'IT', DATE '2017-03-20');
COMMIT;
